apiVersion: v1
kind: Service
metadata:
  name: jupyter
  labels:
    app.kubernetes.io/name: jupyter
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: jupyter
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}