apiVersion: v1
kind: Secret
metadata:
  name: graph-db-secret
  labels:
    app.kubernetes.io/name: graph-db
type: Opaque
stringData:
  NEO4J_AUTH: {{ .Values.neo4j.auth | quote }}
  NEO4J_USER: {{ .Values.neo4j.user | quote }}
  NEO4J_PASSWORD: {{ .Values.neo4j.password | quote }}
