apiVersion: v1
kind: Service
metadata:
  name: graph-db
  labels:
    app.kubernetes.io/name: graph-db
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: graph-db
  ports:
    - name: neo4j-ui
      port: {{ .Values.service.uiPort }}
      targetPort: 7474
      protocol: TCP
    - name: bolt
      port: {{ .Values.service.boltPort }}
      targetPort: 7687
      protocol: TCP