apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: graph-db
  labels:
    app.kubernetes.io/name: graph-db
spec:
  serviceName: graph-db
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: graph-db
  template:
    metadata:
      labels:
        app.kubernetes.io/name: graph-db
    spec:
      containers:
        - name: graph-db
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: neo4j-ui
              containerPort: 7474
            - name: bolt
              containerPort: 7687
          env:
            - name: NEO4J_AUTH
              valueFrom:
                secretKeyRef:
                  name: graph-db-secret
                  key: NEO4J_AUTH
          volumeMounts:
            - name: graph-db-data
              mountPath: /data
          resources:
{{ toYaml .Values.resources | indent 12 }}
  volumeClaimTemplates:
    - metadata:
        name: graph-db-data
        labels:
          app.kubernetes.io/name: graph-db
      spec:
        accessModes:
{{ toYaml .Values.persistence.accessModes | indent 10 }}
        storageClassName: {{ .Values.persistence.storageClassName | quote }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}