replicaCount: 1

image:
  repository: akshay4444/workbench
  tag: chainlit-v3
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8501

ingress:
  enabled: true
  className: nginx
  host: chainlit.unboxitsolutions.in
  scheme: internet-facing
  targetType: ip

config:
  dbHost: vector-db
  dbName: ragdb
  ollamaUrl: http://ollama:11434
  neo4jUri: bolt://graph-db:7687
  langfuseHost: http://54.225.144.31:3000
  llmModel: tinyllama
  embeddingModel: nomic-embed-text

secret:
  dbUser: postgres
  dbPassword: postgres
  neo4jUser: neo4j
  neo4jPassword: password
  langfusePublicKey: pk-lf-861a0b43-8c7d-4b9c-84cb-7a10a9837d42
  langfuseSecretKey: sk-lf-f70f8a61-2c53-4775-940b-dd839695dca4

resources: {}
