apiVersion: v1
kind: Secret
metadata:
  name: chainlit-secret
  labels:
    app.kubernetes.io/name: chainlit
type: Opaque
stringData:
  DB_USER: {{ .Values.secret.dbUser | quote }}
  DB_PASSWORD: {{ .Values.secret.dbPassword | quote }}
  NEO4J_USER: {{ .Values.secret.neo4jUser | quote }}
  NEO4J_PASSWORD: {{ .Values.secret.neo4jPassword | quote }}
  LANGFUSE_PUBLIC_KEY: {{ .Values.secret.langfusePublicKey | quote }}
  LANGFUSE_SECRET_KEY: {{ .Values.secret.langfuseSecretKey | quote }}
